apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-datadb-pvc
spec:
  storageClassName: manual
  selector:
    matchLabels:
      type: mongodb-datadb-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Mi

