apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    type: mongodb-deployment
  name: mongodb-deployment
spec:
  replicas: 3
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.service: mongodb
    spec:
      containers:
      - image: ksravikumar2005/mongo:latest
        name: mongodb
        ports:
        - containerPort: 27017
        resources: {}
      hostname: mongodb
      restartPolicy: Always
status: {}
