apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-datadb-pv
  labels:
    type: mongodb-datadb-pv
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/uservolumes/mongo-datadb"
