---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data-0
  namespace: mongodb
spec:
  storageClassName: mongodb-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data-1
  namespace: mongodb
spec:
  storageClassName: mongodb-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data-2
  namespace: mongodb
spec:
  storageClassName: mongodb-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
