apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    type: mongodb-deployment
  name: mongodb-deployment-0
  namespace: mongodb
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.service: mongodb
    spec:
      containers:
      - image: ksravikumar2005/mongodb:latest
        name: mongodb
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: datadb
      hostname: mongodb
      restartPolicy: Always
      volumes:
      - name: datadb
        persistentVolumeClaim:
          claimName: mongodb-data-0
status: {}

